export const routes = {
  public: {
    home: "/",
    products: "/products",
    categories: "/products",
    categoryDetail: (categorySlug) => `/categories/${categorySlug}`,
    productDetail: (productId) => `/products/${productId}`,
    search: "/search",
    compatibility: "/compatibility",
    checkout: "/checkout",
    trackOrder: "/track-order",
    contact: "/contact",
  },
  customer: {
    account: "/account",
    accountOrders: "/account/orders",
    accountOrderDetail: (orderNumber) => `/account/orders/${orderNumber}`,
    accountPayments: "/account/payments",
    accountReturns: "/account/returns",
    accountInvoices: "/account/invoices",
    accountNotifications: "/account/notifications",
    accountEnquiries: "/account/enquiries",
    accountReviews: "/account/reviews",
    accountQuestions: "/account/questions",
  },
  admin: {
    adminRoot: "/admin",
    adminLogin: "/admin/login",
    adminTotp: "/admin/totp",
    adminDashboard: "/admin/dashboard",
    adminProducts: "/admin/products",
    adminProductNew: "/admin/products/new",
    adminProductDetail: (productId) => `/admin/products/${productId}`,
    adminOrders: "/admin/orders",
    adminOrderDetail: (orderNumber) => `/admin/orders/${orderNumber}`,
    adminPayments: "/admin/payments",
    adminShipments: "/admin/shipments",
    adminCustomers: "/admin/customers",
    adminReviews: "/admin/reviews",
    adminQuestions: "/admin/questions",
    adminEnquiries: "/admin/enquiries",
    adminReturns: "/admin/returns",
    adminRefunds: "/admin/refunds",
    adminInvoices: "/admin/invoices",
    adminAnalytics: "/admin/analytics",
    adminSettings: "/admin/settings",
    adminNotifications: "/admin/notifications",
    adminAuditLogs: "/admin/audit-logs",
  },
};
