export const routes = {
  public: {
    home: "/",
    about: "/about",
    products: "/products",
    categories: "/products",
    categoryDetail: (categorySlug) => `/categories/${categorySlug}`,
    productDetail: (productId) => `/products/${productId}`,
    search: "/search",
    compatibility: "/compatibility",
    checkout: "/checkout",
    checkoutSuccess: "/checkout/success",
    trackOrder: "/track-order",
    contact: "/contact",
    returnPolicy: "/return-policy",
    terms: "/terms",
    privacyPolicy: "/privacy-policy",
  },
  customer: {
    account: "/account",
    accountOrders: "/account/orders",
    accountOrderDetail: (orderNumber) => `/account/orders/${orderNumber}`,
    accountPayments: "/account/payments",
    accountReturns: "/account/returns",
    accountInvoices: "/account/invoices",
    accountNotifications: "/account/notifications",
    accountEnquiries: "/account/enquiries",
    accountReviews: "/account/reviews",
    accountQuestions: "/account/questions",
    accountProfile: "/account/profile",
  },
  admin: {
    adminRoot: "/admin",
    adminLogin: "/admin/login",
    adminTotp: "/admin/totp",
    adminDashboard: "/admin/dashboard",
    adminProducts: "/admin/products",
    adminProductNew: "/admin/products/new",
    adminProductDetail: (productId) => `/admin/products/${productId}`,
    adminCategories: "/admin/categories",
    adminBrands: "/admin/brands",
    adminVehicleModels: "/admin/vehicle-models",
    adminOrders: "/admin/orders",
    adminOrderDetail: (orderNumber) => `/admin/orders/${orderNumber}`,
    adminPayments: "/admin/payments",
    adminShipments: "/admin/shipments",
    adminCustomers: "/admin/customers",
    adminCustomerDetail: (customerId) =>
      `/admin/customers?selected=${encodeURIComponent(customerId)}`,
    adminReviews: "/admin/reviews",
    adminQuestions: "/admin/questions",
    adminEnquiries: "/admin/enquiries",
    adminEnquiryDetail: (enquiryId) =>
      `/admin/enquiries?selected=${encodeURIComponent(enquiryId)}`,
    adminReturns: "/admin/returns",
    adminRefunds: "/admin/refunds",
    adminInvoices: "/admin/invoices",
    adminAnalytics: "/admin/analytics",
    adminSettings: "/admin/settings",
    adminNotifications: "/admin/notifications",
    adminAuditLogs: "/admin/audit-logs",
  },
};
